/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lausebs.eventmng.view;

import com.lausebas.eventmng.model.Artista;
import com.lausebas.eventmng.services.ServicioArtista;
import com.lausebas.eventmng.services.ServicioEvento;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author estigia
 */
public class ActualizarConcierto extends javax.swing.JFrame {

    ServicioEvento servicioEvento;
    ServicioArtista servicioArtista;

    public ActualizarConcierto(ServicioEvento servicioEvento, ServicioArtista servicioArtista) {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        this.servicioEvento = servicioEvento;
        this.servicioArtista = servicioArtista;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFBuscarConcierto = new javax.swing.JTextField();
        pnlCenter = new javax.swing.JPanel();
        lblNLocalidades = new javax.swing.JLabel();
        txtFUbicacion = new javax.swing.JTextField();
        txtFNLocalidades = new javax.swing.JTextField();
        txtFPrecio = new javax.swing.JTextField();
        lblArtista = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblTipoMusica = new javax.swing.JLabel();
        txtFNombre = new javax.swing.JTextField();
        txtFTipoMusica = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        dtcFecha = new com.toedter.calendar.JDateChooser();
        cmbArtista = new javax.swing.JComboBox();
        lblTitulo = new javax.swing.JLabel();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtFBuscarConcierto.setForeground(new java.awt.Color(153, 153, 153));
        txtFBuscarConcierto.setText("Digite el nombre");
        txtFBuscarConcierto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFBuscarConciertoMousePressed(evt);
            }
        });
        txtFBuscarConcierto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFBuscarConciertoActionPerformed(evt);
            }
        });

        pnlCenter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblNLocalidades.setForeground(new java.awt.Color(5, 44, 77));
        lblNLocalidades.setText("Nª Localidades");

        txtFUbicacion.setEditable(false);
        txtFUbicacion.setBackground(new java.awt.Color(185, 209, 226));
        txtFUbicacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFUbicacionActionPerformed(evt);
            }
        });

        txtFNLocalidades.setEditable(false);
        txtFNLocalidades.setBackground(new java.awt.Color(185, 209, 226));
        txtFNLocalidades.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFNLocalidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNLocalidadesActionPerformed(evt);
            }
        });

        txtFPrecio.setEditable(false);
        txtFPrecio.setBackground(new java.awt.Color(185, 209, 226));
        txtFPrecio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFPrecioActionPerformed(evt);
            }
        });

        lblArtista.setForeground(new java.awt.Color(5, 44, 77));
        lblArtista.setText("Artista");

        lblNombre.setForeground(new java.awt.Color(5, 44, 77));
        lblNombre.setText("Nombre");

        lblTipoMusica.setForeground(new java.awt.Color(5, 44, 77));
        lblTipoMusica.setText("Tipo de musica");

        txtFNombre.setEditable(false);
        txtFNombre.setBackground(new java.awt.Color(185, 209, 226));
        txtFNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNombreActionPerformed(evt);
            }
        });

        txtFTipoMusica.setEditable(false);
        txtFTipoMusica.setBackground(new java.awt.Color(185, 209, 226));
        txtFTipoMusica.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFTipoMusica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFTipoMusicaActionPerformed(evt);
            }
        });

        lblFecha.setForeground(new java.awt.Color(5, 44, 77));
        lblFecha.setText("Fecha");

        lblUbicacion.setForeground(new java.awt.Color(5, 44, 77));
        lblUbicacion.setText("Ubicacion");

        lblPrecio.setForeground(new java.awt.Color(5, 44, 77));
        lblPrecio.setText("Precio");

        dtcFecha.setEnabled(false);

        cmbArtista.setBackground(new java.awt.Color(5, 44, 77));
        cmbArtista.setFont(new java.awt.Font("URW Gothic", 0, 12)); // NOI18N
        cmbArtista.setForeground(new java.awt.Color(185, 209, 226));
        cmbArtista.setEnabled(false);
        cmbArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbArtistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addGap(26, 30, Short.MAX_VALUE)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCenterLayout.createSequentialGroup()
                        .addComponent(lblTipoMusica)
                        .addGap(18, 18, 18)
                        .addComponent(txtFTipoMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCenterLayout.createSequentialGroup()
                            .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNLocalidades)
                                .addComponent(lblArtista))
                            .addGap(20, 20, 20)
                            .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFNLocalidades)
                                .addComponent(cmbArtista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlCenterLayout.createSequentialGroup()
                            .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombre)
                                .addComponent(lblFecha)
                                .addComponent(lblUbicacion)
                                .addComponent(lblPrecio))
                            .addGap(47, 47, 47)
                            .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtFUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFNombre)
                                    .addComponent(dtcFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCenterLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(19, 19, 19)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(dtcFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUbicacion)
                    .addComponent(txtFUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(txtFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoMusica)
                    .addComponent(txtFTipoMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNLocalidades)
                    .addComponent(txtFNLocalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblArtista)
                    .addComponent(cmbArtista, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        lblTitulo.setFont(new java.awt.Font("URW Gothic", 1, 22)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(5, 44, 77));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Actualizar Concierto");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        btnActualizar.setBackground(new java.awt.Color(5, 44, 77));
        btnActualizar.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(5, 44, 77));
        btnBuscar.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitulo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFBuscarConcierto, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(pnlCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(124, 124, 124))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFBuscarConcierto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(pnlCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  public void llenarComboBox() {
       cmbArtista.removeAllItems();
        for (Artista nArtista : servicioArtista.listarArtistas()) {
            cmbArtista.addItem(nArtista.getNombre());
        }
    }
    private void txtFBuscarConciertoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFBuscarConciertoMousePressed
        txtFBuscarConcierto.setText("");
        txtFBuscarConcierto.setForeground(Color.black);        // TODO add your handling code here:
    }//GEN-LAST:event_txtFBuscarConciertoMousePressed

    private void txtFBuscarConciertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFBuscarConciertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFBuscarConciertoActionPerformed

    private void txtFUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFUbicacionActionPerformed

    private void txtFNLocalidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNLocalidadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNLocalidadesActionPerformed

    private void txtFPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPrecioActionPerformed

    private void txtFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNombreActionPerformed

    private void txtFTipoMusicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFTipoMusicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFTipoMusicaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            servicioEvento.actualizarConcierto(servicioEvento.buscarConcierto(txtFNombre.getText()),
                    servicioArtista.buscarArtista(cmbArtista.getSelectedItem().toString()),
                    Integer.parseInt(txtFNLocalidades.getText()),
                    txtFTipoMusica.getText(),
                    dtcFecha.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(),
                    txtFUbicacion.getText(),
                    Double.parseDouble(txtFPrecio.getText()));
            JOptionPane.showMessageDialog(this, "El Concierto se actualizo con éxito.");
            
             txtFNombre.setText("");
             txtFUbicacion.setText("");
             dtcFecha.setDate(null);
             txtFPrecio.setText("");
             txtFTipoMusica.setText("");
             txtFNLocalidades.setText("");
             txtFBuscarConcierto.setText("");
             
            txtFUbicacion.setEditable(false);
            dtcFecha.setEnabled(false);
            txtFPrecio.setEditable(false);
            txtFTipoMusica.setEditable(false);
            txtFNLocalidades.setEditable(false);
            cmbArtista.setEnabled(false);
            
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String nombre = txtFBuscarConcierto.getText();
        llenarComboBox();
        try {
            txtFNombre.setText(servicioEvento.buscarConcierto(nombre).getNombre());
            dtcFecha.setDate(Date.from(
                    servicioEvento.buscarConcierto(nombre).getFecha().
                            atStartOfDay(ZoneId.systemDefault()).toInstant()));
            txtFUbicacion.setText(servicioEvento.buscarConcierto(nombre).getUbicacion());
            txtFPrecio.setText(String.valueOf(servicioEvento.buscarConcierto(nombre).getPrecioEntrada()));
            txtFTipoMusica.setText(servicioEvento.buscarConcierto(nombre).getTipoMusica());
            txtFNLocalidades.setText(String.valueOf(servicioEvento.buscarConcierto(nombre).getLocalidades()));
            cmbArtista.setSelectedItem(servicioEvento.buscarConcierto(nombre).getArtista().getNombre());
            txtFUbicacion.setEditable(true);
            dtcFecha.setEnabled(true);
            txtFPrecio.setEditable(true);
            txtFTipoMusica.setEditable(true);
            txtFNLocalidades.setEditable(true);
            cmbArtista.setEnabled(true);
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cmbArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbArtistaActionPerformed

    }//GEN-LAST:event_cmbArtistaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox cmbArtista;
    private com.toedter.calendar.JDateChooser dtcFecha;
    private javax.swing.JLabel lblArtista;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNLocalidades;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipoMusica;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JTextField txtFBuscarConcierto;
    private javax.swing.JTextField txtFNLocalidades;
    private javax.swing.JTextField txtFNombre;
    private javax.swing.JTextField txtFPrecio;
    private javax.swing.JTextField txtFTipoMusica;
    private javax.swing.JTextField txtFUbicacion;
    // End of variables declaration//GEN-END:variables
}
