/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lausebs.eventmng.view;

import com.lausebas.eventmng.services.ServicioEvento;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author estigia
 */
public class AñadirFeriaGastro extends javax.swing.JFrame {

  
       private ServicioEvento servicioEvento;
       
    public AñadirFeriaGastro(ServicioEvento servicioEvento) {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        this.servicioEvento = servicioEvento;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFNStands = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        txtFUbicacion = new javax.swing.JTextField();
        txtFPrecio = new javax.swing.JTextField();
        txtFFechaDIa = new javax.swing.JTextField();
        txtFFechaMes = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        txtFFechaAño = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblTipoCocina = new javax.swing.JLabel();
        txtFNombre = new javax.swing.JTextField();
        txtFTipoCocina = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblNStands = new javax.swing.JLabel();
        lblUbicacion = new javax.swing.JLabel();
        btnAñadir = new javax.swing.JButton();
        chExpandible = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtFNStands.setBackground(new java.awt.Color(185, 209, 226));
        txtFNStands.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFNStands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNStandsActionPerformed(evt);
            }
        });

        lblPrecio.setForeground(new java.awt.Color(5, 44, 77));
        lblPrecio.setText("Precio");

        txtFUbicacion.setBackground(new java.awt.Color(185, 209, 226));
        txtFUbicacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFUbicacionActionPerformed(evt);
            }
        });

        txtFPrecio.setBackground(new java.awt.Color(185, 209, 226));
        txtFPrecio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFPrecioActionPerformed(evt);
            }
        });

        txtFFechaDIa.setBackground(new java.awt.Color(185, 209, 226));
        txtFFechaDIa.setForeground(new java.awt.Color(153, 153, 153));
        txtFFechaDIa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFFechaDIa.setText("D");
        txtFFechaDIa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFFechaDIa.setPreferredSize(new java.awt.Dimension(325, 401));
        txtFFechaDIa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFFechaDIaMousePressed(evt);
            }
        });
        txtFFechaDIa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFFechaDIaActionPerformed(evt);
            }
        });

        txtFFechaMes.setBackground(new java.awt.Color(185, 209, 226));
        txtFFechaMes.setForeground(new java.awt.Color(153, 153, 153));
        txtFFechaMes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFFechaMes.setText("M");
        txtFFechaMes.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFFechaMes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFFechaMesMousePressed(evt);
            }
        });
        txtFFechaMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFFechaMesActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("URW Gothic", 1, 22)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(5, 44, 77));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Añadir Feria Gastro");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        txtFFechaAño.setBackground(new java.awt.Color(185, 209, 226));
        txtFFechaAño.setForeground(new java.awt.Color(153, 153, 153));
        txtFFechaAño.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtFFechaAño.setText("Y");
        txtFFechaAño.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFFechaAño.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtFFechaAñoMousePressed(evt);
            }
        });
        txtFFechaAño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFFechaAñoActionPerformed(evt);
            }
        });

        lblNombre.setForeground(new java.awt.Color(5, 44, 77));
        lblNombre.setText("Nombre");

        lblTipoCocina.setForeground(new java.awt.Color(5, 44, 77));
        lblTipoCocina.setText("Tipo de cocina");

        txtFNombre.setBackground(new java.awt.Color(185, 209, 226));
        txtFNombre.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFNombreActionPerformed(evt);
            }
        });

        txtFTipoCocina.setBackground(new java.awt.Color(185, 209, 226));
        txtFTipoCocina.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(5, 44, 77), 1, true));
        txtFTipoCocina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFTipoCocinaActionPerformed(evt);
            }
        });

        lblFecha.setForeground(new java.awt.Color(5, 44, 77));
        lblFecha.setText("Fecha");

        lblNStands.setForeground(new java.awt.Color(5, 44, 77));
        lblNStands.setText("Nª Stands");

        lblUbicacion.setForeground(new java.awt.Color(5, 44, 77));
        lblUbicacion.setText("Ubicacion");

        btnAñadir.setBackground(new java.awt.Color(5, 44, 77));
        btnAñadir.setFont(new java.awt.Font("URW Gothic", 1, 12)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });

        chExpandible.setForeground(new java.awt.Color(5, 44, 77));
        chExpandible.setText("Expandible");
        chExpandible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chExpandibleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecio)
                            .addComponent(lblNStands)
                            .addComponent(lblUbicacion)
                            .addComponent(lblTipoCocina)
                            .addComponent(lblFecha)
                            .addComponent(lblNombre))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(txtFFechaDIa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFFechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtFFechaAño, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFTipoCocina)
                                .addComponent(txtFUbicacion)
                                .addComponent(txtFPrecio)
                                .addComponent(txtFNStands, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTitulo)))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(chExpandible)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAñadir)
                        .addGap(124, 124, 124))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(22, 22, 22)
                        .addComponent(lblFecha)
                        .addGap(22, 22, 22)
                        .addComponent(lblUbicacion)
                        .addGap(20, 20, 20)
                        .addComponent(lblPrecio)
                        .addGap(20, 20, 20)
                        .addComponent(lblTipoCocina)
                        .addGap(20, 20, 20)
                        .addComponent(lblNStands))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFFechaDIa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFFechaMes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFFechaAño, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(txtFUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFTipoCocina, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFNStands, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(chExpandible, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAñadir)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFNStandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNStandsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNStandsActionPerformed

    private void txtFUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFUbicacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFUbicacionActionPerformed

    private void txtFPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPrecioActionPerformed

    private void txtFFechaDIaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFechaDIaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFechaDIaActionPerformed

    private void txtFFechaMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFechaMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFechaMesActionPerformed

    private void txtFFechaAñoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFFechaAñoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFFechaAñoActionPerformed

    private void txtFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFNombreActionPerformed

    private void txtFTipoCocinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFTipoCocinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFTipoCocinaActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        try{
        servicioEvento.añadirFeriaGastro(servicioEvento.crearFeriaGastro(Integer.parseInt(txtFNStands.getText()),
                                                                                                                                          txtFTipoCocina.getText(),
                                                                                                                                          chExpandible.isSelected(),
                                                                                                                                          txtFNombre.getText(),
                                                                                                                                           LocalDate.of(Integer.parseInt(txtFFechaAño.getText()),
                                                                                                                                                                    Integer.parseInt(txtFFechaMes.getText()), 
                                                                                                                                                                    Integer.parseInt(txtFFechaDIa.getText())),
                                                                                                                                           txtFUbicacion.getText(),
                                                                                                                                           Double.parseDouble(txtFPrecio.getText())));
                     JOptionPane.showMessageDialog(this, "El evento se añadió con éxito.");
                                  txtFNombre.setText("");
             txtFFechaDIa.setText("");
             txtFFechaMes.setText("");
             txtFFechaAño.setText("");
             txtFUbicacion.setText("");
             txtFPrecio.setText("");
             txtFTipoCocina.setText("");
             txtFNStands.setText("");
        }    
        catch (IllegalArgumentException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAñadirActionPerformed
    
    private void chExpandibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chExpandibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chExpandibleActionPerformed

    private void txtFFechaDIaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFFechaDIaMousePressed
        txtFFechaDIa.setText("");
        txtFFechaDIa.setForeground(Color.black);    }//GEN-LAST:event_txtFFechaDIaMousePressed

    private void txtFFechaMesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFFechaMesMousePressed
        txtFFechaMes.setText("");
        txtFFechaMes.setForeground(Color.black);    }//GEN-LAST:event_txtFFechaMesMousePressed

    private void txtFFechaAñoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtFFechaAñoMousePressed
        txtFFechaAño.setText("");
        txtFFechaAño.setForeground(Color.black);
    }//GEN-LAST:event_txtFFechaAñoMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JCheckBox chExpandible;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblNStands;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblTipoCocina;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUbicacion;
    private javax.swing.JTextField txtFFechaAño;
    private javax.swing.JTextField txtFFechaDIa;
    private javax.swing.JTextField txtFFechaMes;
    private javax.swing.JTextField txtFNStands;
    private javax.swing.JTextField txtFNombre;
    private javax.swing.JTextField txtFPrecio;
    private javax.swing.JTextField txtFTipoCocina;
    private javax.swing.JTextField txtFUbicacion;
    // End of variables declaration//GEN-END:variables
}
