/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lausebs.eventmng.view;

import com.lausebas.eventmng.model.FeriaGastronomica;
import com.lausebas.eventmng.services.ServicioEvento;
import com.lausebas.eventmng.services.ServicioObserver;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author estigia
 */
public class ListarFeriaGastro extends javax.swing.JFrame implements Notificable {

    private ServicioEvento servicioEvento;
    private ServicioObserver servicioObserver;
    DefaultTableModel model = new DefaultTableModel();

    public ListarFeriaGastro(ServicioEvento servicioEvento, ServicioObserver servicioObserver) {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        setModelo();
        this.servicioEvento = servicioEvento;
        this.servicioObserver = ServicioObserver.getInstance();
        servicioObserver.añadirigInteresadas(this);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFeria = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("URW Gothic", 1, 32)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(5, 44, 77));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Listado de Ferias Gastro");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tblFeria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Ubicacion", "Precio", "Tipo de Cocina", "Nº Stands"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFeria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lblTitulo)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setModelo() {
        String[] cabecera = {"Nombre", "Fecha", "Ubicacion", "Precio", "Tipo de Cocina", "N Stands"};
        model.setColumnIdentifiers(cabecera);
        tblFeria.setModel(model);
    }
    
    private void listar(){
         model.setRowCount(0);
        for (FeriaGastronomica feriaGastro : servicioEvento.listarFeriasGastronomicas()) {
            Object[] datos = new Object[model.getColumnCount()];
            datos[0] = feriaGastro.getNombre();
            datos[1] = feriaGastro.getFecha().toString();
            datos[2] = feriaGastro.getUbicacion();
            datos[3] = String.format("%.2f", feriaGastro.getPrecioEntrada());
            datos[4] = feriaGastro.getTipoCocina();
            datos[5] = feriaGastro.getNumStands();
            model.addRow(datos);
        }
    }

    @Override
    public void avisoCambio() {
        listar();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblFeria;
    // End of variables declaration//GEN-END:variables

}
