/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.lausebs.eventmng.view;

import com.lausebas.eventmng.model.Concierto;
import com.lausebas.eventmng.services.ServicioEvento;
import com.lausebas.eventmng.services.ServicioObserver;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author estigia
 */
public class ListarConcierto extends javax.swing.JFrame implements Notificable {

    private ServicioEvento servicioEvento;
    private ServicioObserver servicioObserver;
    DefaultTableModel model = new DefaultTableModel();

       
    public ListarConcierto(ServicioEvento servicioEvento, ServicioObserver servicioObserver) {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        setModelo();
        this.servicioEvento = servicioEvento;
        this.servicioObserver = servicioObserver;
        servicioObserver.añadirigInteresadas(this);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFeria = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("URW Gothic", 1, 32)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(5, 44, 77));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Listado de Conciertos");
        lblTitulo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        tblFeria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Ubicacion", "Precio", "Tipo de Musica", "Localidades", "Artista"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFeria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setModelo(){
        String[] cabecera = {"Nombre","Fecha","Ubicacion","Precio","Tipo de Musica","Localidades","Artista"};
        model.setColumnIdentifiers(cabecera);
        tblFeria.setModel(model);
    }
    private void listar(){
        model.setRowCount(0);
        for (Concierto concierto : servicioEvento.listarConciertos()) {
            Object[] datos = new Object[model.getColumnCount()];
           datos[0] = concierto.getNombre();
           datos[1] = concierto.getFecha().toString();
           datos[2] = concierto.getUbicacion();
           datos[3] = String.format("%.2f", concierto.getPrecioEntrada());
           datos[4] = concierto.getTipoMusica();
           datos[5] = concierto.getLocalidades();
           datos[6] = concierto.getArtista().getNombre();
           model.addRow(datos);
        }
             
    }
       @Override
    public void avisoCambio() {
        listar();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblFeria;
    // End of variables declaration//GEN-END:variables

 
}
